jdbc:
    basic:
        maxOpenPreparedStatements: -1
spring:
    h2:
        console:
            enabled: true
    jackson:
        serialization:
            write_dates_as_timestamps: false
    data:
        mongodb:
            uri: mongodb://localhost/test_movie
            database: test_movie
            host: localhost
            port: 27017
